version: '3.9'
services:
  nginx:
    image: "zarak.fr:8092/cache/library/nginx"
    hostname: "nginx"
    container_name: "nginx"
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - worker
    ports:
      - "0.0.0.0:80:80"
    restart: always

  web:
    container_name: "web"
    hostname: "web"
    build: ./web
  worker:
    container_name: "worker"
    hostname: "worker"
    build: ./worker
    depends_on:
      - redis
  redis:
    container_name: "redis"
    hostname: "redis"
    image: "zarak.fr:8092/cache/library/redis"
    restart: always

